# Generated by Django 5.2.10 on 2026-02-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='enlace',
            field=models.URLField(blank=True, help_text='Link del producto (Amazon, etc.)', null=True),
        ),
    ]
