# Generated by Django 5.0 on 2026-02-03 02:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_wishlist_enlace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['tipo', 'nombre'], 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-prioridad', '-creado_en'], 'verbose_name': 'Meta de Ahorro', 'verbose_name_plural': 'Metas de Ahorro'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='color',
            field=models.CharField(default='#6366f1', help_text='Color hex code', max_length=7),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='moneda',
            field=models.CharField(default='USD', help_text='Código de moneda (USD, EUR, etc.)', max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tema_oscuro',
            field=models.BooleanField(default=True, help_text='Preferencia de tema'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='prioridad',
            field=models.IntegerField(default=0, help_text='Mayor número = mayor prioridad'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.CharField(default='bi-tag', help_text='Bootstrap icon class (e.g., bi-cart)', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.categoria'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['usuario', '-fecha'], name='finance_tra_usuario_049602_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['categoria'], name='finance_tra_categor_234c22_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['activo'], name='finance_tra_activo_c93bf3_idx'),
        ),
    ]
