# Generated by Django 5.0 on 2026-02-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_transaccion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inicio_mes',
            field=models.IntegerField(default=1, help_text='Día de inicio del mes financiero (1 o 15)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, help_text='Usuario de Instagram', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Perfil de LinkedIn'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meta_ahorro_mensual',
            field=models.IntegerField(default=20, help_text='Porcentaje de ahorro mensual objetivo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meta_ingreso_mensual',
            field=models.DecimalField(decimal_places=2, default=2000, help_text='Meta de ingreso mensual esperado', max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ocupacion',
            field=models.CharField(blank=True, help_text='Trabajo o estudios', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ciudad, País', max_length=100),
        ),
    ]
